npm start script error in config.json
Removed comma after the first closing bracket that was causing npm start script to fail
```
/var/www/poa-wiki/public_html/sokol-faucet$ npm start

> poa-network-sokol-faucet@1.0.0 start /var/www/poa-wiki/public_html/sokol-faucet
> node index.js

undefined:15
}
^

SyntaxError: Unexpected token } in JSON at position 398
    at Object.parse (native)
    at Object.<anonymous> (/var/www/poa-wiki/public_html/sokol-faucet/index.js:19:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! poa-network-sokol-faucet@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the poa-network-sokol-faucet@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serv2/.npm/_logs/2018-01-29T06_31_05_558Z-debug.log
```